### PR TITLE
Move game logic from window to model

### PR DESCRIPTION
**Pull request by criticalglitch**
Guts the window class and moves logic to the model class. This adds about 20 tests. Resolves issue #68.

### CODE REVIEW

**Review by bakursait2 — CHANGES_REQUESTED** [review]
Great game logic improvements! Ran the game smoothly.
Tests passed, except `test_handle_primary_action_block_hit_is_stone_no_block_removed()` (lines 181-186) which was NOT classified as a `pass` or `fail`.

image

Big improvement, thanks for updating!

**Comment by criticalglitch** [comment]
> Great game logic improvements! Ran the game smoothly. Tests passed, except `test_handle_primary_action_block_hit_is_stone_no_block_removed()` (lines 181-186) which was NOT classified as a `pass` or `fail`.
> 
> Big improvement, thanks for updating!

Good catch, I forgot to rename the function below that one when I copied it.

**Comment by bakursait2** [comment]
The test `test_handle_primary_action_block_hit_is_brick_block_removed()` works perfect now. What was the problem? Is it naming issue?

**Review by bakursait2 — APPROVED** [review]

**Comment by criticalglitch** [comment]
> The test `test_handle_primary_action_block_hit_is_brick_block_removed()` works perfect now. What was the problem? Is it naming issue?

Yes, there were two functions both named `test_handle_primary_action_block_hit_is_stone_no_block_removed`, the issue was fixed by naming the second one to `test_handle_primary_action_block_hit_is_brick_block_removed`

**Review by xieWright — APPROVED** [review]
Looks like another refactorization. Seems okay to pass since the tests haven't borked out and the game works on my comp.

**Review by w1158mxs — APPROVED** [review]

**Review by Lurk390 — APPROVED** [review]
All changes look fine and the tests pass, look good to merge

**Pull request merged**
