### PR TITLE
Added BackgroundNoise class and implemented background sounds in game.

### PR DESCRIPTION
**Pull request by xieWright**
Added the feature of background noise into the game. New class is for repeating sounds and will be modified as needed.

### CODE REVIEW

**Review by criticalglitch — APPROVED** [review]

**Review by bakursait2 — CHANGES_REQUESTED** [review]
Every thing looks great. However, When exiting the game, an error shows up (and the game terminated):

Screenshot from 2023-07-17 00-12-22

Can we fix that?
Thanks.

**Review by Lurk390 — APPROVED** [review]
Looks good. We should probably implement a sound control system for adjusting the volume level sooner rather than later.

**Comment by criticalglitch** [comment]
> Every thing looks great. However, When exiting the game, an error shows up (and the game terminated):
> 
> Screenshot from 2023-07-17 00-12-22
> 
> Can we fix that? Thanks.

I think this particular issue might be an issue on your machine. On my machine I'm not able to reproduce this bug and I've started and closed the game several times in rapid succession.

I'm noticing that pyglet decided to use OpenAL on your machine versus on mine its using PulseAudio, so I think it might be a bug in the audio backend you're using which is out of our control.

**Review by criticalglitch — CHANGES_REQUESTED** [review]
While reviewing PR #83, I noticed a crash that was repeatable though inconsistent in timing. Investigating it further I traced it down to the sound system you implemented.

To reproduce it, fly around while spamming block breaks. After a minute or two this causes the program to crash with a Segmentation Fault.

I think it has something to do with the way we're queueing up events and playing them.

**Comment by xieWright** [comment]
In regards to that, I think that's another issue in a way that's unrelated to this one.  That would be a bugfix in regards to how sounds are being handled in the event, in this case in the destruction of blocks. It is unrelated to the playback of background sounds and should be handled in another branch as another issue.

**Review by criticalglitch — APPROVED** [review]

**Pull request merged**
