### PR TITLE
Pass-through-clouds issue #57

### PR DESCRIPTION
**Pull request by bakursait2**
Solve [Issue#57](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/57)

**Features added to main.py:**
- Create `is_it_cloud_block()` that will return a boolean statement whether the current player coordinates represents a cloud block (light or dark cloud).
- The function `is_it_cloud_block()` is called within the already-defined `collide()` function that checks and takes an action whether the player hit some objects or not.

**test_minecraft.py:**

- Added some tests that check the `is_it_cloud_block()` functionality with all objects (LIGHT_CLOUD, DARK_CLOUD, STONE, BRICK, GRASS, SAND, ...) in the game.

### CODE REVIEW

**Review by w1158mxs — APPROVED** [review]
this is more understandable variables

**Review by Lurk390 — APPROVED** [review]
These changes look good. The only concern is that my pull request #53 will probably break these tests, so I will probably need your help fixing that.

**Comment by w1158mxs** [comment]
When I Play it I can see lines between blocks! even in clouds

**Comment by Lurk390** [comment]
> When I Play it I can see lines between blocks! even in clouds

I saw this too but I don't think it was from any changes done here. See Issue #62

**Comment by bakursait2** [comment]
> When I Play it I can see lines between blocks! even in clouds

Yeah.. That is weird. I can see lines surrounding all kind of blocks. this is not the case in the earlier versions.

The only changes that I made are 1. inside the `collide()` function. 2. create `is_it_cloud_block()` function. and I believe non of which has to do with drawing that line.

**Comment by bakursait2** [comment]
> These changes look good. The only concern is that my pull request #53 will probably break these tests, so I will probably need your help fixing that.

sure will help.

**Review by criticalglitch — APPROVED** [review]

**Review by w1158mxs — APPROVED** [review]

**Comment by bakursait2** [comment]
It passes all the checks.
Now merging [Issue#57](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/57)

**Comment by bakursait2** [comment]
I took a screenshot of the test code result. 
I ran the command: `poetry run pytest --cov` and it shows the following:

Screenshot from 2023-07-26 14-12-51

**Pull request merged**
