### PR TITLE
Player create dark clouds

### PR DESCRIPTION
**Pull request by w1158mxs**
If anyone wants to block building anything on clouds please create a new issue and do it!

My customer wants to build his house on the clouds so I need to do [issue#33] & [issue#34]

The player will use key down 6 to build light clouds, and 7 to build dark clouds because [issue#80] builds trees and leaves using Key down 4&5.

### CODE REVIEW

**Review by xieWright — APPROVED** [review]
Looking over these changes, it's not too big a change. As far as I can tell, it's mostly just changing the properties of the cloud blocks to be breakable and being able to use them as building blocks. This will need to be merged first.

**Review by Lurk390 — APPROVED** [review]
Looks fine to me and passing all the tests.

**Review by bakursait2 — APPROVED** [review]
Passed the tests and the new code looks like adjusting the property of the clouds to be attachable.

**Review by criticalglitch — CHANGES_REQUESTED** [review]
Please rebase your PR, there are conflicts.

**Comment by w1158mxs** [comment]
> Please rebase your PR, there are conflicts.

Since I created this branch from another branch #105 
so I need to rebase #107 first, isn't it?

**Review by criticalglitch — APPROVED** [review]
OK

**Pull request merged**
