### PR TITLE
Test results mass

### PR DESCRIPTION
**Pull request by w1158mxs**
[issue#108] Done .. Result of statistics
s: seconds
up to Date:26-7-2023
The computer used for test speed is attached with pictures

first test time = 6.87s
first passed count: 6
Avg = pass per 1,145s

last test time = 58.16s
last test count: 130
Avg = pass per 0.447

[issue#108] Results
Last test time - first test time = 51.29s for 124 passes
Avg: = pass per 0.413

Conclusion: test time avg getting lower with more tasks
summary: we can't know if this test is the best without comparing it with another test!
Recommendation: Merge all test files and do this study again to see who is faster!

### CODE REVIEW

**Review by Lurk390 — COMMENTED** [review]
You don't need a pull request for test results, we have automated testing through GitHub Actions. What the professor meant is that for every pull request **before** adding the automated testing, you should add a comment to the closed pull request with a screenshot of the test. You should not add screenshots to the source code as you've done here.

**Comment by bakursait2** [comment]
I totally agree with @Lurk390 . 
We need to add a screenshot of the tests into the PR.

**Comment by w1158mxs** [comment]
> You don't need a pull request for test results, we have automated testing through GitHub Actions. What the professor meant is that for every pull request **before** adding the automated testing, you should add a comment to the closed pull request with a screenshot of the test. You should not add screenshots to the source code as you've done here.

this issue is to calculate different test speeds also between the first test and the last per second!
I agree with others... Thank you

**Comment by xieWright** [comment]
Gonna close this PR since it seems to be a misunderstanding.

**Pull request closed without merging**
